### ISSUE TITLE
Not an issue but a help for a newbie

### ISSUE THREAD

**Issue by Sag-Aiden** [kykc/MsiFanControl#15]
Im new to this github stuff and knows very basic stuff how to download the program and run it. But i guess i need some guide to install this program as the program is not installing just by double clicking it(cmd pops and closes in a second). I know i might be annoying but someone teach me how to

**Comment by kykc** [comment]
I guess it's not connected to the github much if you've downloaded prebuilt binary from [here](https://github.com/kykc/MsiFanControl/releases/tag/v1.2)

The thing is that this is a command line utility. In order to use it you will need to make use of the terminal. Depending on your settings and the version of Windows you're using your mileage may vary. I guess universal way would be to press `Win+R` type `cmd` into prompt and press enter. In the new terminal Window navigate to the directory (using `cd`) where you've unzipped the binary archive and try to run `MsiFanControl.exe install`. Then you can try to apply settings/profiles as decribed in the [README.md](https://github.com/kykc/MsiFanControl?tab=readme-ov-file#using).

Sadly I won't be able to provide much support as I no longer have any MSI laptops.

**Comment by Sag-Aiden** [comment]
OMG it works. I didnt had the knowledge of cd command in command prompt (im noob i learnt today after seeing ur reply) and it worked perfect!!!!!!!!!!!THANK YOU SO MUCH IT WILL BE REALLY HELPFUL FOR ME AND MY FRIENDS

**Comment by kykc** [comment]
Glad to be of help, at least some of my time wasn't wasted 😄
